### ISSUE TITLE
template example not working in angular 14 with lit  2.2.4

### ISSUE THREAD

**Issue by jitendraP-ashutec** [justinfagnani/stampino#41]
I have tried to given example to create web component in lit version 2.2.4 and in angular 14. 

```
<template id="my-template">
  <h1>Hello {{ name }}</h1>
</template>


import * as stampino from 'stampino';
import {render} from 'lit';

const templateElement = document.querySelector('#my-template');

// Returns a lit-html template function that accepts data and
// returns a renderable TemplateResult
const myTemplate = stampino.prepareTemplate(templateElement);

render(myTemplate({name: 'World'}), document.body);

```

but its not working.  Do you have any suggestion for it?

**Comment by bennypowers** [comment]
In which browser did you try this?

**Comment by jitendraP-ashutec** [comment]
I am trying in chrome. Version 106.0.5249.119 (64-bit)

**Comment by justinfagnani** [comment]
Stampino has been updated to use lit-html 3, and importantly not to use the private signal from a lit-html 2.0 prerelease that was removed before 2.0 final. If that was the issue, things should work now.

I'm going to close this since it's quite old, but feel free to reopen if this is still an issue.
